// parse-pr-receipt.test.ts — fixture-based tests for the PR-body receipt parser.
//
// Run: deno test --allow-none supabase/functions/major-github-webhook/parse-pr-receipt.test.ts
// (no network/env needed — pure function)
//
// Coverage targets the acceptance criteria from issue #52:
//   (a) Prose mention does NOT match.
//   (b) Code-block mention does NOT match.
//   (c) Implementer-emitted `## Linked` footer form DOES match.
//   (d) Legacy `Major-item:` form within `## Linked` DOES match.

import { assertEquals } from "jsr:@std/assert@^0.226.0";
import { parseBriefIdFromBody } from "./parse-pr-receipt.ts";

// ────────────────────────────────────────────────────────────────────
// Positive cases — receipt is correctly extracted
// ────────────────────────────────────────────────────────────────────

Deno.test("(c) implementer-emitted Linked footer with current Major-brief", () => {
  // Mirrors the exact shape `shell/prompts/implementer.md` emits.
  const body = `## Summary

Tidy bug fix.

## Files touched

- src/foo.ts

## Verification (sandbox)

- typecheck: pass
- tests: pass (\`npm test\`)

## Linked

Major-brief: 42
Run: 10610

🤖 Generated by Tachikoma (implementer@2026-05-10)
`;
  assertEquals(parseBriefIdFromBody(body), 42);
});

Deno.test("(d) legacy Major-item form inside Linked section still matches", () => {
  const body = `## Linked

Major-item: 13
`;
  assertEquals(parseBriefIdFromBody(body), 13);
});

Deno.test("matches receipt even when other prose elsewhere mentions the format", () => {
  // This is the exact shape that bit us in issue #52 — prose mentioning a
  // receipt-shaped literal alongside the real receipt in Linked.
  const body = `## Summary

PR #51 broke because its body said \`Major-item: 10\` in prose. This PR fixes the parser.

## Linked

Major-brief: 42
Run: 12345
`;
  assertEquals(parseBriefIdFromBody(body), 42);
});

Deno.test("matches the first receipt when Linked contains multiple", () => {
  const body = `## Linked

Major-brief: 42
Major-brief: 99
`;
  assertEquals(parseBriefIdFromBody(body), 42);
});

// ────────────────────────────────────────────────────────────────────
// Negative cases — receipt is NOT extracted (the issue #52 protection)
// ────────────────────────────────────────────────────────────────────

Deno.test("(a) prose mention outside Linked does NOT match", () => {
  const body = `## Summary

We discovered the cross-wire when PR #51 said \`Major-item: 10\` in its description.
`;
  assertEquals(parseBriefIdFromBody(body), null);
});

Deno.test("(b) code-block mention outside Linked does NOT match", () => {
  const body = `## Background

The parser used to match this:

\`\`\`
Major-brief: 99
\`\`\`
`;
  assertEquals(parseBriefIdFromBody(body), null);
});

Deno.test("receipt-shaped line in a different H2 section does NOT match", () => {
  // No `## Linked` heading at all → return null even if a receipt-shaped
  // line appears in `## Background`.
  const body = `## Background

Major-brief: 77
`;
  assertEquals(parseBriefIdFromBody(body), null);
});

Deno.test("receipt appearing AFTER Linked in a subsequent H2 does NOT match", () => {
  // Anchoring on `## Linked` stops at the next H2, so a receipt in a
  // later section doesn't accidentally count.
  const body = `## Linked

(intentionally no receipt yet)

## Notes

Major-brief: 99
`;
  assertEquals(parseBriefIdFromBody(body), null);
});

Deno.test("empty Linked section returns null", () => {
  const body = `## Summary

Bla.

## Linked

`;
  assertEquals(parseBriefIdFromBody(body), null);
});

Deno.test("receipt mid-line inside Linked does NOT match", () => {
  // The implementer prompt emits the receipt on its own line; only that
  // form is accepted.
  const body = `## Linked

See Major-brief: 42 (it's the test brief).
`;
  assertEquals(parseBriefIdFromBody(body), null);
});

Deno.test("indented receipt inside Linked does NOT match (must be column 0)", () => {
  const body = `## Linked

    Major-brief: 42
`;
  assertEquals(parseBriefIdFromBody(body), null);
});

// ────────────────────────────────────────────────────────────────────
// Edge cases — null / undefined / empty input
// ────────────────────────────────────────────────────────────────────

Deno.test("empty string returns null", () => {
  assertEquals(parseBriefIdFromBody(""), null);
});

Deno.test("null body returns null", () => {
  assertEquals(parseBriefIdFromBody(null), null);
});

Deno.test("undefined body returns null", () => {
  assertEquals(parseBriefIdFromBody(undefined), null);
});

Deno.test("body with only a Linked heading and no other content returns null", () => {
  assertEquals(parseBriefIdFromBody("## Linked"), null);
});
