// Major v1 — TypeScript types for the `major.*` schema.
//
// One exported type per table, named in PascalCase singular.
// snake_case columns map to camelCase fields.
// String-literal unions mirror SQL CHECK constraints; export them so callers
// (functions, shell, ui) can use them in switches without re-deriving.
//
// Conventions:
// - `bigserial` / `bigint` columns → `number`. Supabase-js returns these as
//   numbers when they fit in a JS-safe integer; the orchestrator runs at low
//   volumes so this is fine for v1. Bump to `string` if we ever exceed 2^53.
// - `timestamptz` columns → `Date | string`. Postgres returns ISO strings over
//   the wire; some SDKs parse to Date. Allow both.
// - `jsonb` columns default to `Record<string, unknown>` unless SPEC pins a
//   shape. Where it does (events.payload, telemetry.payload, etc.), a
//   discriminated union or sub-type is provided and re-exported.
// - This file is generated by hand from `0001_initial_schema.sql`. When the
//   schema changes, update both. There is no codegen step in v1.
//
// In-code identifiers and Postgres tables both use the GITS vocabulary
// (Brief / Shell / briefId / shellId in code; briefs / shells / brief_id /
// shell_id in `major.*`) per ADR 004.

// ────────────────────────────────────────────────────────────────────
// Enum-like string unions
// ────────────────────────────────────────────────────────────────────

export type BriefStatus =
  | 'ready-for-triage'
  | 'needs-info'
  | 'ready-for-agent'
  | 'agent-running'
  | 'ready-for-review'
  | 'ready-for-human'
  | 'merge-blocked'
  | 'done'
  | 'wontfix';

export type BriefClassification =
  | 'bug-fix'
  | 'feature'
  | 'refactor'
  | 'docs'
  | 'parent'
  | 'epic';

export type ArtifactType = 'git-change' | 'triage-change-set';

export type PullRequestStatus = 'absent' | 'open' | 'merged' | 'closed';

export type RelationshipType = 'parent-child' | 'blocks';

export type ParentReviewRequirement = 'required' | 'optional' | 'excluded';

export type RunPurpose = 'execute' | 'review' | 'triage' | 'repair';

export type RunOutcome = 'running' | 'succeeded' | 'failed' | 'cancelled';

export type RunCancellationReason =
  | 'human-cancellation'
  | 'system-cancellation'
  | 'lease-expired'
  | 'repair-acquisition';

export type VerificationOutcome = 'pass' | 'fail' | 'skipped';

export type VerificationRequirednessSource =
  | 'artifact-type-policy'
  | 'ready-for-agent-content'
  | 'human-override'
  | 'automated-acceptance-policy';

export type TriageSessionStatus = 'open' | 'closed';

export type TriageChangeSetDecision =
  | 'proposed'
  | 'accepted'
  | 'rejected'
  | 'superseded';

export type TriageChangeOperationType =
  | 'create-brief'
  | 'add-content-revision'
  | 'set-classifications'
  | 'add-relationship'
  | 'set-parent-review-requirement'
  | 'record-git-branch'
  | 'set-ready-state'
  | 'set-queue-rank'
  | 'transition-brief';

export type TriageChangeOperationStatus =
  | 'proposed'
  | 'accepted'
  | 'rejected'
  | 'applied'
  | 'failed'
  | 'skipped'
  | 'blocked';

export type AutoTriageRequestStatus =
  | 'requested'
  | 'running'
  | 'completed'
  | 'failed'
  | 'cancelled'
  | 'superseded';

// Actor strings are formatted as `<kind>:<name>` (e.g. `human:jonathan`,
// `shell:shell-A`, `agent:tachikoma`, `integration:github`,
// `major:auto-triage`, `major:reaper`). Stored as plain text — typed open here
// so callers can compose without constant re-narrowing.
export type ActorKind = 'human' | 'agent' | 'shell' | 'integration' | 'major';
export type ActorString = `${ActorKind}:${string}`;

// Common Event types observed in SPEC. Open via `(string & {})` so
// integrations adding new event names don't require a types.ts change.
export type KnownEventType =
  | 'brief-created'
  | 'status-transitioned'
  | 'run-started'
  | 'run-ended'
  | 'accepted'
  | 'rejected'
  | 'human-handoff'
  | 'relationship-added'
  | 'content-revision-added'
  | 'artifact-produced'
  | 'queue-rank-set';
export type EventType = KnownEventType | (string & Record<never, never>);

// Common Telemetry observation types observed in SPEC. Open in the same way.
export type KnownTelemetryObservation =
  | 'failed-claim-attempt'
  | 'heartbeat-lapse'
  | 'external-system-error'
  | 'retry-attempt'
  | 'repair-inspection-trigger';
export type TelemetryObservationType =
  | KnownTelemetryObservation
  | (string & Record<never, never>);

// ────────────────────────────────────────────────────────────────────
// JSONB payload sub-types
// ────────────────────────────────────────────────────────────────────

// `events.payload` — discriminated by `events.type`. Only the types where
// SPEC pins a shape are enumerated; the catch-all branch keeps the door open.
export type EventPayload =
  | { kind: 'status-transitioned'; from: BriefStatus; to: BriefStatus; reason?: string }
  | { kind: 'run-started'; runId: number; purpose: RunPurpose; revisionId?: number }
  | {
      kind: 'run-ended';
      runId: number;
      outcome: Exclude<RunOutcome, 'running'>;
      cancellationReason?: RunCancellationReason;
    }
  | { kind: 'human-handoff'; reason: string; expectedAction?: string }
  | {
      kind: 'artifact-produced';
      artifactId: number;
      artifactType: ArtifactType;
      externalRef?: string;
    }
  | { kind: 'relationship-added'; relationshipId: number; type: RelationshipType }
  | { kind: 'content-revision-added'; revisionId: number; revisionNumber: number }
  | { kind: 'queue-rank-set'; queueRank: number; previous?: number }
  | { kind: 'accepted'; prUrl?: string }
  | { kind: 'rejected'; reason?: string }
  | { kind: 'brief-created'; sourceSessionId?: number }
  | Record<string, unknown>;

// `shells.metadata` — container provenance.
export type ShellMetadata = {
  containerId?: string;
  imageTag?: string;
  host?: string;
  [extra: string]: unknown;
};

// `runs.log_artifact_refs` — array of pointers to log blobs.
export type RunLogArtifactRef = {
  kind: 'sandbox-stdout' | 'sandbox-stderr' | 'tachikoma-transcript' | (string & Record<never, never>);
  uri: string;
  bytes?: number;
  [extra: string]: unknown;
};

// `triage_change_sets.blocker_reasons` — which path-blocker rules tripped.
export type PathBlockerReason = {
  rule: 'glob-intersection' | 'mass-rerank' | (string & Record<never, never>);
  matchedGlob?: string;
  matchedPath?: string;
  reason?: string;
  [extra: string]: unknown;
};

// `triage_sessions.transcript` — chat history; not lifecycle-authoritative.
export type TriageTranscriptMessage = {
  role: 'user' | 'assistant' | 'system' | (string & Record<never, never>);
  content: string;
  ts: string; // ISO timestamp, set client-side
  [extra: string]: unknown;
};

// `triage_change_operations.payload` — discriminated by `operation_type`.
// Each op carries exactly the fields needed to apply it.
export type TriageChangeOperationPayload =
  | {
      type: 'create-brief';
      classifications: BriefClassification[];
      expectedArtifactType?: ArtifactType;
      expectedPaths?: string[];
      gitRepositoryRef?: string;
      baseBranch?: string;
      contentMd: string;
      placementReason?: string;
    }
  | {
      type: 'add-content-revision';
      briefId: number;
      contentMd: string;
      reason?: string;
    }
  | {
      type: 'set-classifications';
      briefId: number;
      classifications: BriefClassification[];
    }
  | {
      type: 'add-relationship';
      parentId: number;
      childId: number;
      relationship: RelationshipType;
      parentReviewRequirement?: ParentReviewRequirement;
    }
  | {
      type: 'set-parent-review-requirement';
      relationshipId: number;
      parentReviewRequirement: ParentReviewRequirement;
      excludedReason?: string;
      excludedRevisionId?: number;
    }
  | {
      type: 'record-git-branch';
      briefId: number;
      gitRepositoryRef: string;
      gitBranch: string;
      baseBranch?: string;
    }
  | {
      type: 'set-ready-state';
      briefId: number;
      expectedArtifactType: ArtifactType;
      expectedPaths: string[];
    }
  | {
      type: 'set-queue-rank';
      briefId: number;
      queueRank: number;
      priorityClass?: string;
      placementReason?: string;
    }
  | {
      type: 'transition-brief';
      briefId: number;
      to: BriefStatus;
      reason?: string;
    };

// `triage_change_operations.resulting_record_ref` — pointer to created/modified row.
export type TriageChangeOperationResultRef = {
  table: string;
  id: number | string;
  [extra: string]: unknown;
};

// `verification_results.payload` — output snippet, link to artifact.
export type VerificationResultPayload = {
  outputSnippet?: string;
  artifactRef?: string;
  durationMs?: number;
  [extra: string]: unknown;
};

// `brief_artifacts.payload` — artifact-type-specific extra detail.
export type BriefArtifactPayload = {
  // git-change
  baseSha?: string;
  headSha?: string;
  prNumber?: number;
  // triage-change-set
  changeSetId?: number;
  [extra: string]: unknown;
};

// ────────────────────────────────────────────────────────────────────
// Table row types
// ────────────────────────────────────────────────────────────────────

export type GithubIssueTriggerPayload = {
  source_issue_repo: string;
  source_issue_number: number;
  source_issue_title: string;
};

export type TriageSession = {
  id: number;
  initiatorActor: ActorString;
  status: TriageSessionStatus;
  transcript: TriageTranscriptMessage[];
  draftPrd: string | null;
  entryPoint: string | null;
  triggerPayload: GithubIssueTriggerPayload | Record<string, unknown> | null;
  createdAt: Date | string;
  updatedAt: Date | string;
};

export type Brief = {
  id: number;
  status: BriefStatus;
  classifications: BriefClassification[];
  expectedArtifactType: ArtifactType | null;
  expectedPaths: string[];
  gitRepositoryRef: string | null;
  gitBranch: string | null;
  baseBranch: string | null;
  prStatus: PullRequestStatus;
  prUrl: string | null;
  queueRank: number | null;
  priorityClass: string | null;
  placementReason: string | null;
  sourceSessionId: number | null;
  // GitHub issue that originated the Brief (ADR 007). Populated by
  // major-create-triage-session when the trigger was 'integration:github'
  // with an issue payload; null for human-initiated triage and synthetic
  // seeds. Read by the PR-merge webhook to close the source issue at
  // Brief done transition.
  sourceIssueRepo: string | null;
  sourceIssueNumber: number | null;
  currentRevisionId: number | null;
  // Per-Brief auto-retry cap (ADR 014). Default 3; overridable per-Brief
  // via Triage. The Shell's finalization compares the failed Run's
  // attempt_number against this cap to decide auto-retry vs park.
  maxAttempts: number;
  createdAt: Date | string;
  updatedAt: Date | string;
};

export type BriefContentRevision = {
  id: number;
  briefId: number;
  revisionNumber: number;
  contentMd: string;
  authorActor: ActorString;
  reason: string | null;
  createdAt: Date | string;
};

export type BriefRelationship = {
  id: number;
  parentId: number;
  childId: number;
  type: RelationshipType;
  parentReviewRequirement: ParentReviewRequirement;
  excludedReason: string | null;
  excludedByActor: ActorString | null;
  excludedRevisionId: number | null;
  createdAt: Date | string;
};

export type Shell = {
  id: string;
  heartbeatAt: Date | string;
  startedAt: Date | string;
  stoppedAt: Date | string | null;
  metadata: ShellMetadata;
};

export type Run = {
  id: number;
  briefId: number;
  purpose: RunPurpose;
  outcome: RunOutcome;
  cancellationReason: RunCancellationReason | null;
  shellId: string | null;
  startedAgainstRevisionId: number | null;
  claimedAt: Date | string | null;
  leaseExpiresAt: Date | string | null;
  heartbeatAt: Date | string | null;
  sandboxRef: string | null;
  logArtifactRefs: RunLogArtifactRef[];
  inspectedRunId: number | null;
  startedAt: Date | string;
  endedAt: Date | string | null;
  // Stream-json Tachikoma telemetry summary metrics (ADR 006). Populated
  // inside the Run Finalization Transaction from the final completion event;
  // null on Runs that finalized before stream-json adoption.
  numTurns: number | null;
  durationMs: number | null;
  finalText: string | null;
  inputTokens: number | null;
  outputTokens: number | null;
  cacheReadTokens: number | null;
  cacheWriteTokens: number | null;
  // Per-event Telemetry sequence counter (ADR 006). Atomically incremented
  // per stream-json event write; the Run-scoped counter underwrites the
  // (run_id, 'tachikoma-stream-event', shell_id, sequence) idempotency key.
  // Never null — defaults to 0 on insert.
  tachikomaEventSequence: number;
  // Which attempt this Run is, per Brief (ADR 014). Reset to 1 on a new
  // Content Revision; otherwise prior Run's attempt_number + 1. Computed
  // inside the Run Start Transaction in major-claim-brief.
  attemptNumber: number;
};

export type ArtifactTypeContract = {
  artifactType: ArtifactType;
  claimAuthority: string[];
  produceAuthority: string[];
  reviewAuthority: string[];
  verifyRequired: string[];
  acceptanceAuthority: string[];
  description: string | null;
};

export type BriefArtifact = {
  id: number;
  briefId: number;
  runId: number | null;
  artifactType: ArtifactType;
  externalRef: string | null;
  payload: BriefArtifactPayload;
  createdAt: Date | string;
};

export type VerificationResult = {
  id: number;
  runId: number;
  checkName: string;
  outcome: VerificationOutcome;
  required: boolean;
  requirednessSource: VerificationRequirednessSource | null;
  payload: VerificationResultPayload;
  createdAt: Date | string;
};

export type TriageChangeSet = {
  id: number;
  triageSessionId: number | null;
  autoTriageRunId: number | null;
  decision: TriageChangeSetDecision;
  decisionActor: ActorString | null;
  decidedAt: Date | string | null;
  summary: string | null;
  needsHumanApply: boolean;
  blockerReasons: PathBlockerReason[];
  createdAt: Date | string;
};

export type TriageChangeOperation = {
  id: number;
  changeSetId: number;
  operationType: TriageChangeOperationType;
  payload: TriageChangeOperationPayload;
  status: TriageChangeOperationStatus;
  idempotencyKey: string;
  appliedActor: ActorString | null;
  appliedAt: Date | string | null;
  resultingRecordRef: TriageChangeOperationResultRef | null;
  sequenceIndex: number;
  createdAt: Date | string;
};

export type AutoTriageRequest = {
  id: number;
  briefId: number;
  status: AutoTriageRequestStatus;
  requestedActor: ActorString;
  requestedRevisionId: number | null;
  resultingRunId: number | null;
  notes: string | null;
  createdAt: Date | string;
  updatedAt: Date | string;
};

export type Event = {
  id: number;
  briefId: number | null;
  runId: number | null;
  type: EventType;
  actor: ActorString;
  payload: EventPayload;
  idempotencyKey: string;
  createdAt: Date | string;
};

export type TelemetryRecord = {
  id: number;
  briefId: number | null;
  runId: number | null;
  observationType: TelemetryObservationType;
  payload: Record<string, unknown>;
  // Added by migration 20260509000006 — null for records written before ADR 005.
  idempotencyKey: string | null;
  createdAt: Date | string;
};

export type PathBlockerConfig = {
  id: 1; // singleton
  protectedGlobs: string[];
  massRerankThreshold: number;
  updatedAt: Date | string;
  updatedBy: ActorString;
};
