-- 20260513000000_apply_change_set_source_issue_attribution.sql
-- Implements issue #80 (ADR 010 inbound attribution).
--
-- Extends apply_change_set: when applying a create-brief op, look up the
-- parent Triage Session's trigger_payload and entry_point via the Change
-- Set's triage_session_id. If the session was GitHub-seeded
-- (entry_point = 'integration:github'):
--
--   1. Populate source_issue_repo / source_issue_number on the new Brief
--      from trigger_payload (preferred over the op-level payload fallback).
--
--   2. Set the initial Content Revision's author_actor to
--      'agent:triage-tachikoma' rather than the calling human actor —
--      the revision was generated by the Triage Tachikoma, not the human
--      who pressed "Apply".
--
-- Sessions with no trigger_payload (human-initiated) are unchanged:
--   - source_issue_* fall back to the op payload (typically null).
--   - author_actor remains p_actor (the calling human).
--
-- The session lookup is a single SELECT inside the same Postgres transaction
-- as the apply loop — no additional round-trips from the application layer.
--
-- Depends on:
--   20260510000000_briefs_source_issue.sql      (source_issue_* columns exist)
--   20260511000000_triage_sessions_entry_point.sql  (entry_point, trigger_payload)
--   20260512000001_rpc_v2_stream_b.sql          (prior apply_change_set body)

set search_path = major, public;

begin;

create or replace function major.apply_change_set(
  p_change_set_id    bigint,
  p_actor            text,
  p_idempotency_root text default null
)
returns table (
  applied_op_count integer,
  failed_op_id     bigint,
  failure_message  text
) language plpgsql security definer as $$
declare
  v_op             record;
  v_payload        jsonb;
  v_count          integer := 0;
  v_idem_root      text    := coalesce(p_idempotency_root, p_change_set_id::text);
  v_new_brief_id   bigint;
  v_new_revision   bigint;
  v_existing_max   integer;
  v_current_status text;
  v_target_status  text;
  -- Session attribution: loaded once and reused across all create-brief ops
  -- in this Change Set. Null when the Change Set has no triage_session_id
  -- (e.g. auto-triage runs whose change sets are linked via auto_triage_run_id).
  v_session_entry_point     text;
  v_session_trigger_payload jsonb;
begin
  -- Load the parent session's entry_point and trigger_payload once, at the
  -- start of the transaction. Left join because triage_session_id is nullable
  -- (auto-triage change sets have no session row).
  select ts.entry_point, ts.trigger_payload
  into   v_session_entry_point, v_session_trigger_payload
  from   major.triage_change_sets cs
  left join major.triage_sessions ts on ts.id = cs.triage_session_id
  where  cs.id = p_change_set_id;

  for v_op in
    select id, operation_type, payload, sequence_index
    from major.triage_change_operations
    where change_set_id = p_change_set_id
      and status in ('proposed', 'accepted')
    order by sequence_index asc
    for update
  loop
    v_payload := v_op.payload;

    -- Resolve the __auto__ placeholder: if the payload's brief_id is the
    -- sentinel "__auto__", substitute the id of the Brief most recently
    -- created in this same change set by a create-brief op.
    if v_new_brief_id is not null and (v_payload->>'brief_id') = '__auto__' then
      v_payload := jsonb_set(v_payload, '{brief_id}', to_jsonb(v_new_brief_id));
    end if;

    if v_op.operation_type = 'create-brief' then
      insert into major.briefs (
        status, classifications, expected_artifact_type, expected_paths,
        git_repository_ref, base_branch, queue_rank, priority_class, placement_reason,
        source_session_id, source_issue_repo, source_issue_number
      ) values (
        'ready-for-triage',
        coalesce((v_payload->'classifications')::text[]::text[], '{}'),
        v_payload->>'expected_artifact_type',
        coalesce(array(select jsonb_array_elements_text(v_payload->'expected_paths')), '{}'),
        v_payload->>'git_repository_ref',
        coalesce(v_payload->>'base_branch', 'dev'),
        nullif((v_payload->>'queue_rank'), '')::integer,
        v_payload->>'priority_class',
        v_payload->>'placement_reason',
        nullif((v_payload->>'source_session_id'), '')::bigint,
        -- Prefer the parent session's trigger_payload for source-issue attribution
        -- when it is present (GitHub-seeded sessions). Fall back to the op-level
        -- payload fields for backward compatibility with ops that carry them
        -- directly, and to null for human-initiated sessions.
        coalesce(
          nullif(v_session_trigger_payload->>'source_issue_repo', ''),
          nullif(v_payload->>'source_issue_repo', '')
        ),
        coalesce(
          nullif(v_session_trigger_payload->>'source_issue_number', '')::integer,
          nullif(v_payload->>'source_issue_number', '')::integer
        )
      )
      returning id into v_new_brief_id;

      if v_payload ? 'content_md' then
        insert into major.brief_content_revisions (
          brief_id, revision_number, content_md, author_actor, reason
        ) values (
          v_new_brief_id, 1, v_payload->>'content_md',
          -- For GitHub-seeded sessions the Content Revision was generated by
          -- the Triage Tachikoma, not the calling human who pressed "Apply".
          case when v_session_entry_point = 'integration:github'
               then 'agent:triage-tachikoma'
               else p_actor
          end,
          'create-brief'
        )
        returning id into v_new_revision;

        update major.briefs set current_revision_id = v_new_revision where id = v_new_brief_id;
      end if;

      insert into major.events (brief_id, type, actor, payload, idempotency_key)
      values (
        v_new_brief_id, 'brief-created', p_actor,
        jsonb_build_object('change_set_id', p_change_set_id, 'sequence_index', v_op.sequence_index),
        'brief-created:' || v_new_brief_id::text || ':' || v_idem_root
      );

      update major.triage_change_operations
      set status = 'applied', applied_actor = p_actor, applied_at = now(),
          resulting_record_ref = jsonb_build_object('brief_id', v_new_brief_id, 'revision_id', v_new_revision)
      where id = v_op.id;

    elsif v_op.operation_type = 'add-content-revision' then
      select coalesce(max(revision_number), 0) into v_existing_max
      from major.brief_content_revisions
      where brief_id = (v_payload->>'brief_id')::bigint;

      insert into major.brief_content_revisions (
        brief_id, revision_number, content_md, author_actor, reason
      ) values (
        (v_payload->>'brief_id')::bigint,
        v_existing_max + 1,
        v_payload->>'content_md',
        p_actor,
        v_payload->>'reason'
      )
      returning id into v_new_revision;

      update major.briefs
      set current_revision_id = v_new_revision
      where id = (v_payload->>'brief_id')::bigint;

      insert into major.events (brief_id, type, actor, payload, idempotency_key)
      values (
        (v_payload->>'brief_id')::bigint, 'content-revision-added', p_actor,
        jsonb_build_object('revision_id', v_new_revision, 'reason', v_payload->>'reason'),
        'content-revision-added:' || v_new_revision::text || ':' || v_idem_root
      );

      update major.triage_change_operations
      set status = 'applied', applied_actor = p_actor, applied_at = now(),
          resulting_record_ref = jsonb_build_object('revision_id', v_new_revision)
      where id = v_op.id;

    elsif v_op.operation_type = 'set-classifications' then
      update major.briefs
      set classifications = coalesce(array(select jsonb_array_elements_text(v_payload->'classifications')), '{}')
      where id = (v_payload->>'brief_id')::bigint;

      update major.triage_change_operations
      set status = 'applied', applied_actor = p_actor, applied_at = now()
      where id = v_op.id;

    elsif v_op.operation_type = 'add-relationship' then
      insert into major.brief_relationships (
        parent_id, child_id, type, parent_review_requirement
      ) values (
        (v_payload->>'parent_id')::bigint,
        (v_payload->>'child_id')::bigint,
        v_payload->>'type',
        coalesce(v_payload->>'parent_review_requirement', 'required')
      )
      on conflict (parent_id, child_id, type) do nothing;

      insert into major.events (brief_id, type, actor, payload, idempotency_key)
      values (
        (v_payload->>'child_id')::bigint, 'relationship-added', p_actor,
        v_payload,
        'relationship-added:' || (v_payload->>'parent_id') || ':' || (v_payload->>'child_id') || ':' || v_idem_root
      );

      update major.triage_change_operations
      set status = 'applied', applied_actor = p_actor, applied_at = now()
      where id = v_op.id;

    elsif v_op.operation_type = 'set-parent-review-requirement' then
      update major.brief_relationships
      set parent_review_requirement = v_payload->>'value',
          excluded_reason           = v_payload->>'reason',
          excluded_by_actor         = p_actor
      where id = (v_payload->>'relationship_id')::bigint;

      update major.triage_change_operations
      set status = 'applied', applied_actor = p_actor, applied_at = now()
      where id = v_op.id;

    elsif v_op.operation_type = 'record-git-branch' then
      update major.briefs
      set git_branch  = v_payload->>'git_branch',
          base_branch = coalesce(v_payload->>'base_branch', base_branch)
      where id = (v_payload->>'brief_id')::bigint;

      update major.triage_change_operations
      set status = 'applied', applied_actor = p_actor, applied_at = now()
      where id = v_op.id;

    elsif v_op.operation_type = 'set-ready-state' then
      -- Resolve target status from the payload's 'ready' boolean.
      v_target_status := case when (v_payload->>'ready')::boolean
                              then 'ready-for-agent' else 'ready-for-triage' end;

      -- F-04 server-side path-blocker check (defense-in-depth, Hard Rule 5).
      if v_target_status = 'ready-for-agent'
         and major.brief_paths_blocked((v_payload->>'brief_id')::bigint) then
        raise exception 'path-blocker violation on set-ready-state: brief % expected_paths intersect protected_globs (Hard Rule 5)',
          v_payload->>'brief_id';
      end if;

      -- Transition validation (F-22): only fires when the Brief exists.
      select status into v_current_status
      from major.briefs where id = (v_payload->>'brief_id')::bigint
      for update;

      if found then
        if v_target_status not in (
          select unnest(allowed)
          from (values
            ('ready-for-triage',  array['needs-info','ready-for-agent','wontfix']::text[]),
            ('needs-info',        array['ready-for-triage','wontfix']::text[]),
            ('ready-for-agent',   array['agent-running','ready-for-triage','needs-info','wontfix']::text[]),
            ('agent-running',     array['ready-for-review','ready-for-human','ready-for-agent','wontfix']::text[]),
            ('ready-for-review',  array['ready-for-human','done','merge-blocked','wontfix']::text[]),
            ('ready-for-human',   array['done','wontfix','ready-for-triage','ready-for-agent']::text[]),
            ('merge-blocked',     array['ready-for-review','done','wontfix']::text[]),
            ('done',              array[]::text[]),
            ('wontfix',           array[]::text[])
          ) as t(from_status, allowed)
          where from_status = v_current_status
        ) then
          raise exception 'invalid transition from % to % for brief %',
            v_current_status, v_target_status, v_payload->>'brief_id';
        end if;
      end if;

      update major.briefs
      set status = v_target_status
      where id = (v_payload->>'brief_id')::bigint;

      insert into major.events (brief_id, type, actor, payload, idempotency_key)
      values (
        (v_payload->>'brief_id')::bigint, 'status-transitioned', p_actor,
        v_payload,
        'status-transitioned-srs:' || (v_payload->>'brief_id') || ':' || v_idem_root || ':' || v_op.sequence_index
      );

      update major.triage_change_operations
      set status = 'applied', applied_actor = p_actor, applied_at = now()
      where id = v_op.id;

    elsif v_op.operation_type = 'set-queue-rank' then
      update major.briefs
      set queue_rank       = nullif(v_payload->>'queue_rank', '')::integer,
          priority_class   = v_payload->>'priority_class',
          placement_reason = v_payload->>'placement_reason'
      where id = (v_payload->>'brief_id')::bigint;

      insert into major.events (brief_id, type, actor, payload, idempotency_key)
      values (
        (v_payload->>'brief_id')::bigint, 'queue-rank-set', p_actor,
        v_payload,
        'queue-rank-set:' || (v_payload->>'brief_id') || ':' || v_idem_root || ':' || v_op.sequence_index
      );

      update major.triage_change_operations
      set status = 'applied', applied_actor = p_actor, applied_at = now()
      where id = v_op.id;

    elsif v_op.operation_type = 'transition-brief' then
      -- F-04 server-side path-blocker check (defense-in-depth, Hard Rule 5).
      if v_payload->>'to_status' = 'ready-for-agent'
         and major.brief_paths_blocked((v_payload->>'brief_id')::bigint) then
        raise exception 'path-blocker violation on transition-brief: brief % expected_paths intersect protected_globs (Hard Rule 5)',
          v_payload->>'brief_id';
      end if;

      -- Transition validation (F-22).
      select status into v_current_status
      from major.briefs where id = (v_payload->>'brief_id')::bigint
      for update;

      if found then
        if v_payload->>'to_status' not in (
          select unnest(allowed)
          from (values
            ('ready-for-triage',  array['needs-info','ready-for-agent','wontfix']::text[]),
            ('needs-info',        array['ready-for-triage','wontfix']::text[]),
            ('ready-for-agent',   array['agent-running','ready-for-triage','needs-info','wontfix']::text[]),
            ('agent-running',     array['ready-for-review','ready-for-human','ready-for-agent','wontfix']::text[]),
            ('ready-for-review',  array['ready-for-human','done','merge-blocked','wontfix']::text[]),
            ('ready-for-human',   array['done','wontfix','ready-for-triage','ready-for-agent']::text[]),
            ('merge-blocked',     array['ready-for-review','done','wontfix']::text[]),
            ('done',              array[]::text[]),
            ('wontfix',           array[]::text[])
          ) as t(from_status, allowed)
          where from_status = v_current_status
        ) then
          raise exception 'invalid transition from % to % for brief %',
            v_current_status, v_payload->>'to_status', v_payload->>'brief_id';
        end if;
      end if;

      update major.briefs
      set status = v_payload->>'to_status'
      where id = (v_payload->>'brief_id')::bigint;

      insert into major.events (brief_id, type, actor, payload, idempotency_key)
      values (
        (v_payload->>'brief_id')::bigint, 'status-transitioned', p_actor,
        v_payload,
        'status-transitioned-tb:' || (v_payload->>'brief_id') || ':' || v_idem_root || ':' || v_op.sequence_index
      );

      update major.triage_change_operations
      set status = 'applied', applied_actor = p_actor, applied_at = now()
      where id = v_op.id;

    else
      raise exception 'unknown operation_type %', v_op.operation_type;
    end if;

    v_count := v_count + 1;
  end loop;

  update major.triage_change_sets
  set decision = 'accepted', decision_actor = p_actor, decided_at = now()
  where id = p_change_set_id;

  applied_op_count := v_count;
  failed_op_id     := null;
  failure_message  := null;
  return next;
end;
$$;

grant execute on function major.apply_change_set(bigint, text, text) to service_role;

commit;
